# 10-12-2017 MRC-Epid JHZ

db <- Sys.getenv("_db")
options(width=200)
set.seed(31415625)

nw <- read.table(paste0(db,".network"),as.is=TRUE,header=TRUE,quote="")
Raw <- nw[,-1]
tRaw <- t(Raw)
corRaw <- cor(Raw)
colnames(corRaw) <- rownames(corRaw) <- names(Raw)
require(reshape)
r <- melt(corRaw)
e <- cbind(r[1],r[3],r[2])
write.table(e,file="network.sif",col.names=FALSE,row.names=FALSE,quote=FALSE)
m <- (abs(corRaw)>0.7)+0
diag(m) <- 0
z <- gzfile("id_descrip.txt.gz")
id_descrip <- read.table(z,sep="\t",as.is=TRUE,header=TRUE,quote="")
descrip <- id_descrip[with(id_descrip,gsub(":",".",Original.gene.set.ID))%in%names(Raw),"Original.gene.set.description"]
names(Raw) <- gsub(" ",".",descrip)

pdf("network.pdf")
require(igraph)
g <- graph.adjacency(m)
plot(g)
write_graph(g,"network.el","edgelist")
require(cluster)
cl <- kmeans(distance,5,nstart=20)
require(factoextra)
fviz_cluster(cl,data=distance)
distance <- as.dist(1-abs(corRaw))
plot(pam(distance,5))
require(network)
n <- network(m, directed=FALSE)
plot(n)
require(apcluster)
apres <- apcluster(corSimMat,tRaw,details=TRUE)
show(apres)
heatmap(apres)
## change as appropriate
if(0) { 
  require(graph)
  gmat <- new("graphAM", adjMat=m, edgemode='undirected')
  glist <- as(gmat, 'graphNEL')
  plot(glist)
  gap_stat <- clusGap(tRaw, FUN=kmeans, nstart=25, K.max=10, B=5)
  fviz_dist(distance,gradient=list(low="#00AFBB",mid="white",high="#FC4E07"))
  fviz_gap_stat(gap_stat)
  fviz_nbclust(tRaw, kmeans, method="gap_stat", nboot=5)
  require(NbClust)
  nb <- NbClust(tRaw,distance="euclidean",min.nc=2,max.nc=10,method="kmeans",index="all")
  require(RCytoscape)
  require(spatstat)
  plot(im(corRaw[nrow(corRaw):1,]),main="Correlation Matrix Map")
  require(pvclust)
  cl.bootstrap <- pvclust(Raw,nboot=1000,method.dist="correlation")
  plot(cl.bootstrap)
  pvrect(cl.bootstrap)
}
dev.off()
